Feature/admin access
mux99/pocket-bot pull request #10
Opened 2023-10-19 07:53 UTC by Amauryeen

Cette fonctionnalité rajoute une route uniquement accessible aux administrateurs.

# Utilisation de la route
La route est **/admin/***. Toutes les requêtes effectuées sont soumises à la "Protection administrateur". L'accès y est donc très limité.

# Table admins
Une nouvelle table "admins" a été créée dans la base de données. Cette table référence la table "users". La table possède un champs "user_id", donc dès qu'un utilisateur y est rajouté, il est considéré comme étant administrateur.

# Protection administrateur
Une protection empêche l'accès à la route **/admin/*** si l'utilisateur n'est pas dans la table "admins", en le redirigeant vers **/**. Si l'utilisateur est dans la base de données "admins", alors l'accès lui est accordé.

2023-10-19 09:02 UTC, Karitchi commented
Je pense que le code est bon mais donc tu regarde juste si l'utilisateur est admin c'est ça?
Aussi, le seed fonctionne pas chez moi, normalement il faut juste que tu rajoute des `;` après chaque requête.

2023-10-19 09:03 UTC, Karitchi commented
Et il faudrait ajouter admin_id comme primary key dans la table admins pour les identifier.

2023-10-19 09:15 UTC, MachiganMC commented
> Et il faudrait ajouter admin_id comme primary key dans la table admins pour les identifier.

La primary key de cette table, ça pourrait pas être l'id de l'utilisateur ? Y a moyen qu'un champ soit clé primaire et étrangère, ça permettrait de rajouter un champ pour rien.

2023-10-19 15:04 UTC, Karitchi commented on src/hooks.server.js
> +testConnection(pool);
Ici je vois que t'as enlevé le await il y à une raison? Parce que pour moi il faut vraiment le mettre.

2023-11-15 08:05 UTC, Amauryeen commented on src/hooks.server.js
> +testConnection(pool);
Hello. En effet oui. "await" doit être utilisé dans une fonction asynchrone dans l'attente d'une promise et ne peut donc pas fonctionner de façon autonome comme cela.

Une façon d'utiliser async serait la suivante:
`(async () => { await testConnection(pool); })();`

2023-11-15 08:08 UTC, Amauryeen commented on src/hooks.server.js
> +testConnection(pool);
Voici l'erreur donnée par eslint à ce sujet:
![image](https://github.com/mux99/pocket-bot/assets/32741920/548f32d2-7f86-4c71-bc6c-2baa57e522b4)

2023-11-15 08:10 UTC, Amauryeen commented
Les différents problèmes ont été résolus.

- user_id est désormais une PK dans la table admins.
- La seed fonctionne désormais.

2023-11-15 23:02 UTC, MachiganMC requested changes
Hello, j'ai eu quelques soucis avec cette PR :
Pour commencer, dans le fichier `account.js`, il manque l'accolade fermante à la fonction `getUserId` (*voir dans les suggestions de code*). Du coup, le code était inexécutable.

Je suis pas trop fan de vérifier si l'utilisateur est admin via les hooks, ceux-ci ayant beaucoup de problèmes (*j'aimerai bien d'ailleurs les supprimer complètement*). Je n'ai, d'ailleurs, pas su accéder à la page admin même en étant connecté avec un utilisateur admin. Je suggèrerai, donc, de vérifier si l'utilisateur est admin via un fichier `+page.server.js` :
```js
import {checkIfAdmin} from "$lib/server/account.js";
import {redirect} from "@sveltejs/kit";

export const load = async (serverLoadEvent) => {
    if(!await checkIfAdmin(serverLoadEvent))
        throw redirect(308, '/');
}
```
Il serait placé dans le même dossier que ton fichier `+page.svelte`, donc dans le dossier `src/routes/admin`.
Il faudrait donc, supprimer dans le fichier `hook.server.js` :
```js
if (event.url.pathname.startsWith('/admin')) {
	const isAdmin = await checkIfAdmin(event);
	if (!isAdmin) throw redirect(308, '/');
}
```
Et là, on a plus aucun soucis de cache avec les hooks.

J'ai quelques soucis avec le code, pour ça je te laisse regarder les suggestions de code, j'ai tout expliqué dedans. Je vais juste insister sur une qui pourrait poser des problèmes si pas prise en compte.
Dans la fonction `checkIfAdmin` du fichier `account.js`, il faudrait vérifier si `userInfo` est présent dans le stockage locale, car s'il n'y est pas (*ce qui m'est arrivé*), il y a une exception.

2023-11-15 23:49 UTC, MachiganMC commented
Yop, j'ai supprimé ma remarque par rapport au changement de type de la colonne `user_id` pour la table admin. J'ai compris pourquoi t'avais mis le type à **INT**.

2023-11-16 11:28 UTC, MachiganMC approved these changes
C'est bon tout a été corrigé et ça fonctionne bien

2023-11-16 11:30 UTC, merged