Login
mux99/pocket-bot pull request #21
Opened 2023-11-02 17:26 UTC by noelibon

### src/lib/server/account.js
* fonction ```checkIfUsernameExists``` vérifie si le nom d'utilisateur entré côté client existe dans la base de données
* fonction ```checkIfPasswordIsCorrect``` vérifie si le mot de passe entré côté client est correcte
* fonction ```getUserId``` retourne l'id de l'utilisateur correspondant au nom d'utilisateur

### src/routes/login/+page.server.js
* ```default``` est l'action par défaut du formulaire
* + crée une session de connection pour le client
* + si les identifiants sont corrects, retourne un message de succès
* + sinon retourne un message d'erreur

### src/routes/login/+page.svelte
* formulaire de connection
* + si les identifiants sont corrects, affiche un message de succès en vert
* + sinon affiche un message d'erreur en rouge

### src/hooks.server.js
* redirige le client vers la page d'accueil s'il est connecté

### src/routes/+layout.svelte
* importe les utilitaires tailwind pour le css

2023-11-06 22:56 UTC, MachiganMC requested changes
Au niveau du fonctionnel, le code marche parfaitement aucun soucis.
Je me suis permis de suggérer quelques modifications au niveau du code (*majoritairement des déclarations de variables inutiles*), mais c'est juste au niveau "*propreté*" du code. Donc, c'est pas grave si c'est pas modifié.

J'ai juste quelques soucis au niveau "*design*" :

- [ ]  Le formulaires colle trop de le dessus et la gauche de la page (ce serait pas mieux de le centrer au milieux de la page ?)
- [ ] J'ai pas très bien compris l'utilité du "*/ Login /*". On ne peut pas interagir avec, c'est fait exprès ?
- [ ] Ce serait top d'ajouter un bouton "Je n'ai pas de compte" (*qui mènerait vers la page d'inscription*), comme on est de base redirigé sur cette base lorsqu'on est pas connecté.
- [ ] Il pourrait être bien d'ajouter une checkbox "Afficher le mot de passe".

Pour moi, faut juste corriger ces 4 soucis et c'est bon !

2023-11-06 22:56 UTC, MachiganMC commented on src/lib/server/account.js
> +};
Idem que pour `checkIfUsernameExists()`
```suggestion
	return rows[0].id;
}
```

2023-11-06 22:56 UTC, MachiganMC commented on src/routes/login/+page.server.js
> +        if (!check1) {
On a pas besoin de la variable `check1`
```suggestion
        if (!await checkIfUsernameExists(locals, username)) {
```

2023-11-06 22:56 UTC, MachiganMC commented on src/routes/login/+page.server.js
> +        if (!check2) {
On a pas besoin de la variable `check2`
```suggestion
        if (!await checkIfPasswordIsCorrect(locals, username, password)) {
```

2023-11-06 22:56 UTC, MachiganMC commented on src/hooks.server.js
> +};
J'avoue que je comprends pas l'ajout du `;` qui n'est pas obligatoire ?

2023-11-08 00:09 UTC, noelibon commented
Je viens de régler tes remarques @MachiganMC :
* suppression des points-virgules et variables inutiles
* alignement du formulaire au centre
* suppression du "/ Login /"
* ajout du lien vers la page de création de compte
* par contre, la checkbox pour visualiser le mdp était déjà présente

2023-11-08 12:54 UTC, MachiganMC approved these changes
Hello, c'est nickel ! 
Je vois juste pas la checkbox pour les mots de passe, mais à ce niveau là c'est du chipotage.
Du coup, je merge.
![image](https://github.com/mux99/pocket-bot/assets/67206102/17b75492-4d5a-41ed-b802-8ac58af2b732)

2023-11-08 12:56 UTC, merged

2023-11-08 15:39 UTC, noelibon commented
L'oeil (checkbox) apparait lorsque tu cliques sur le champ et que tu tapes le mdp.