Voir les parties jouées
mux99/pocket-bot pull request #23
Opened 2023-11-08 23:22 UTC by MachiganMC

## Description 
Cette pull request permet à l'utilisateur de voir les informations par rapport aux parties qu'il a ,précédemment, jouées.
Il lui sera possible de voir combien de parties il a gagnées/perdues ainsi que de les trier par :
- date,
- durée,
- gagné
- perdu
Le bouton permettant de reproposer une partie à un adversaire sera fonctionnel lorsque la fonctionnalité permettant de créer des parties sera implémentée.

## Préparation :
Pour pouvoir tester cette PR, il est indispensable de mettre à jour la base de données à partir du fichier [`schema.sql`](https://github.com/mux99/pocket-bot/blob/d3de8a59c766af119611abbd2f444e6ea542c263/scripts/schema.sql) afin d'avoir les tables qui ont été crées. 
*Il peut être intéressant aussi d'exécuter le fichier [`seed.sql`](https://github.com/mux99/pocket-bot/blob/d3de8a59c766af119611abbd2f444e6ea542c263/scripts/seed.sql) afin d'avoir des données avec lesquelles travaillées. Il est conseillé de se connecter à l'utilisateur **2** (Bob), celui-ci ayant le plus de parties.*

## Routes :
La nouvelle page est disponible à l'adresse `/parts`. Dans le futur, il peut-être intéressant de déplacer la page à `/profile/parts`.

2023-11-09 11:01 UTC, noelibon requested changes
La PR est fonctionnelle et belle intégration tailwind, juste quelques points à noter:
* problèmes de redirection, mais c'est ma faute donc c'est moi qui réglerai ce problème
* faute d'orthographe dans ```scripts/schema.sql``` lors de la référence de ```part_id``` qui a un 's' en trop (voir plus bas)
* manque d'un point-virgule à la fin de la dernière ligne d'insertion de la table ```sessions``` dans ```scripts/seed.sql``` (voir plus bas)
* dans ```src/app.html```, utile mais peut-être pas approprié dans cette PR
* dans ```src/hooks.server.js```, idem

Sinon c'est parfait, surtout j'ai bien aimé la création du composant dans ```src/lib/components/ArchivePart.svelte``` qui facilite la compréhension et le développement.

2023-11-09 11:02 UTC, noelibon requested changes

2023-11-09 11:02 UTC, noelibon commented on scripts/schema.sql
> +    CONSTRAINT pk_archive_parts PRIMARY KEY (parts_id),
```suggestion
    CONSTRAINT pk_archive_parts PRIMARY KEY (part_id),
```

2023-11-09 11:02 UTC, noelibon commented on scripts/seed.sql
> +  (5, 'b531c4e2-3459-4e83-955c-942f71d52137', '2023-10-19 08:43:46.562+00')
```suggestion
  (5, 'b531c4e2-3459-4e83-955c-942f71d52137', '2023-10-19 08:43:46.562+00');
```

2023-11-12 14:10 UTC, MachiganMC commented
Hello, merci pour les retours @noelibon 
J'ai corrigé tout ce que tu m'avais demandé.
Je n'ai juste pas compris ta remarque :
> dans src/hooks.server.js, idem
Je n'ai pas touché à ce fichier dans cette PR.

2023-11-15 21:01 UTC, noelibon commented
> Hello, merci pour les retours @noelibon J'ai corrigé tout ce que tu m'avais demandé. Je n'ai juste pas compris ta remarque :
> 
> > dans src/hooks.server.js, idem
> 
> Je n'ai pas touché à ce fichier dans cette PR.

OK, parfait.

Oui dans ```src/hooks.server.js```, je voulais parler de l'exporatation de la pool de la base de données, mais c'est pas grave laisse-la, car une PR rien que pour ça c'est abusé.

2023-11-15 21:01 UTC, noelibon approved these changes

2023-11-15 21:06 UTC, merged

2023-11-16 21:52 UTC, MachiganMC commented
Bonjour Mr @julien00859, je me permets de vous mentionner sur cette pull request suite à ce que vous nous avez dit cette après-midi pour avoir votre avis, mais aussi pour revenir sur cette histoire de rebase la branche et qu'on ait tous les commits de la branche principale affichée.
Merci d'avance et bonne soirée

2023-11-20 21:06 UTC, Julien00859 reviewed
The message on the pull request is nice, it is a shame that it is absent from the commit messages. It is also a shame that none of the commits reference the US/issue. Note that the issue is empty, I don't know if this is expected.

Remember that what you write on the pull request is only going to be read by reviewers, what are left to the other devs are the commit messages. So it is the commit messages that matter and not the pull request.

The is all the information that is visible to others and it is not enough:

![image](https://github.com/mux99/pocket-bot/assets/8208953/f1aa1c4b-432f-444e-b498-8419295dd795)

The review from @noelibon is nice, this is the kind of review that I expect: the code as been read, the feature has been tested, good job! You correctly included the requested changes, this is nice too. Regarding the history there is a missed opportunity to merge the 5 commits that together implement the feature together. Taken individually, they do not make any sense, they only make sense when all taken together: they should be inside a single commit.

![image](https://github.com/mux99/pocket-bot/assets/8208953/d88e725b-a821-431a-8c4c-e980c8accec5)

Regarding the unittest this is going to be very easy to review. There are no unittest.

Overall rating: 1/3. 0/1 for the commits, missing commit message and missing references. 1/1 for the review, the code was reviewed and improved, testing was done. 0/1 for the unittests, there are no automated tests.

2023-11-20 21:10 UTC, Julien00859 commented
I suggest you use `git notes` to add the missing reference to the 5 commits that together implement the feature. I suggest you reference this pull request right away, usually we reference the issue/user-story but since it is empty and that the PR is merged let's reference the PR.