Feature/register
mux99/pocket-bot pull request #27
Opened 2023-11-18 17:06 UTC by Karitchi

Révision de la page d'inscription - Version 2

Mises à jour apportées :
- Affichage simultané de toutes les erreurs à l'utilisateur, au lieu de montrer uniquement celles liées au nom d'utilisateur s'il était déjà pris.
- Amélioration du design pour se raprocher d'avantage de la maquette.

2023-11-18 20:48 UTC, MachiganMC requested changes
Hello, j'aime beaucoup les modifications y a juste 2 ou 3 trucs qu'(il faudrait changer, ça concerne pas réellement cette PR, mais ça aurait dû été fait lors de la PR #4.

Ce serait bien d'avoir un champ pour confirmer son mot de passe ainsi que la possibilité de l'afficher. Pour une page d'inscription, c'est super important d'être sûr d'avoir le mis de mot de passe qu'on souhaitait avoir.

Lors d'une erreur sur l'inscription (*nom d'utilisateur ou mot de passe*), la page se rafraîchit ce qui fait qu'on perd le contenu du formulaire et c'est vite embêtant (*surtout quand l'erreur concerne le mot de passe*). 
Pour corriger ça, c'est super simple, tu dois juste ajouter 2 lignes dans ton `+page.svelte` :
```html
<script>
	import {enhance} from "$app/forms"; // importer 'enhance'
	export let form;
</script>
...
<form
	method="post"
	class="bg-modal rounded-3xl flex flex-col gap-8 p-8 justify-center text-3xl"
	use:enhance
<!-- et l'utiliser -->
>
```
Grâce à ces 2 nouvelles lignes, la page ne se rafraichira plus lors de l'envoi du formulaire et donc plus de perte sur le formulaire.

Et pour finir, y a juste des commentaires qui traînent dans le code (*voir la suggestion*).

2023-11-18 20:48 UTC, MachiganMC commented on src/lib/server/account.js
> +	// }
Une utilité à ces commentaires ?
```suggestion

```

2023-11-19 12:39 UTC, Karitchi commented on src/lib/server/account.js
> +	// }
non, je les ai enlevé dans le dernier commit.

2023-11-19 12:51 UTC, Karitchi commented
J'ai enlevé les commentaires et ajouté enhance.

Je vais ajouter un bouton pour permettre de voir le mot de passe, mais pour la confirmation de mot de passe, je préfère ne pas l'implémenter pour l'instant, puisque ce n'est pas dans l'US et que ça prendrait quand même pas mal de temps que je pourrais mettre sur le développement d'une autre US.

Si ça te va, on merge une fois que j'aurai ajouté la fonctionnalité pour voir le mot de passe, et si j'ai du temps, je réouvrirai la PR pour implémenter la confirmation?

2023-11-19 15:30 UTC, Karitchi commented
Voilà, normalement la branche est prête pour le merge.

2023-11-19 20:38 UTC, MachiganMC commented
Je regarde ça !

2023-11-19 22:30 UTC, MachiganMC approved these changes
Nickel tout est bon ! 
Pas de soucis, pour la confirmation de mot de passe, l'affichage est nickel !

2023-11-20 10:15 UTC, Karitchi commented
Je vais simplement merge sans rebase pour cette branche ci, ça va être trop compliqué de réécrire tout l'historique de la branche puisqu'elle est vraiment longue et qu'une v1 avait déjà été merge dans main.

2023-11-20 10:16 UTC, merged