fix: Redirect bug for logged-in users
mux99/pocket-bot pull request #28
Opened 2023-11-19 11:56 UTC by Karitchi

Description:

Modified redirect status code from 8 (permanent) to 7 (temporary) to prevent incorrect redirection of logged-in users to the login page. Users can now navigate between pages without encountering redirection issues. Root Cause:
The previous redirect status code of 8, intended for permanent redirects, caused caching issues in browsers. When a user attempted to access the "/" route, the browser would immediately redirect to "/login" without sending a request to the server for the "/" route, treating the redirect as permanent.

Resolution:

Altered the redirect status code from 8 to 7, ensuring that browsers correctly handle the redirect as temporary and send a request to the server for the "/" route.

2023-11-19 13:06 UTC, MachiganMC commented
So if I understood, the status code when redirecting is really important ? And it was the cause of the issue with the redirection ?

2023-11-19 13:10 UTC, Karitchi commented
Yep, en gros résumé, code 308 = chrome considère qu'il ne doit même pas demander `/` au serveur et il redirige lui-même l'utilisateur vers `/login`

2023-11-19 14:47 UTC, MachiganMC commented
Ok ok, je comprends mieux pourquoi on devait vider le cache. Merci pour les explications !
Je review la PR et je la rebaserai, une fois que c'est fait

2023-11-19 14:59 UTC, Karitchi commented
Ok parfait, par contre review et merge la pr sur github plutôt que de rebase. Normalement rebase c'est pour bouger ta propre branche sur le dernier commit de main, faut jamais rebase les branches des autres.

2023-11-19 17:16 UTC, MachiganMC commented
Je t'explique sur le discord, car Mr Castiaux m'avait donné pas mal d'infos par rapport à ça

2023-11-19 22:40 UTC, MachiganMC requested changes
J'ai encore des problèmes de redirections :
- La page `/rgister` n'est pas accessible depuis la barre de recherche (*quand tu tapes le lien directement*), par contre elle est accessible depuis la page `/login` avec le bouton *Don't have an account ? Register*.
- Lorsqu'on est connecté, on peut toujours accéder à la page `/login`, même après plusieurs raffraîchissements

2023-11-20 10:06 UTC, Karitchi commented
Je viens de push une nouvelle version qui corrige le bug de non redirection des utilisateurs connectés.

Si tu as toujours un problème pour accéder à `/register`, c'est peut-être parce que tu t'es fait rediriger avec un code 308 en exécutant le code d'une autre branche. Si c'est le cas, essaie de vider le cache de Chrome avant de tester cette branche.

Chez moi, ça marche nickel.

2023-11-20 20:39 UTC, MachiganMC approved these changes
Hello, c'est bon tout marche bien !
Y a juste un tout petit soucis avec le nouveau tests d'égalité (*voir en dessous*), mais je pense pas que ça posera un soucis un jour, donc la PR est validée pour moi.

2023-11-20 20:39 UTC, MachiganMC commented on src/hooks.server.js
> +	if (event.locals.userInfo && (event.url.pathname == '/login' || event.url.pathname == '/register')) {
```suggestion
	if (event.locals.userInfo && (event.url.pathname === '/login' || event.url.pathname === '/register')) {
```

2023-11-21 16:30 UTC, Karitchi commented on src/hooks.server.js
> +	if (event.locals.userInfo && (event.url.pathname == '/login' || event.url.pathname == '/register')) {
Parfait, je change ça et je merge.

2023-11-21 16:52 UTC, merged