Feature/roles
mux99/pocket-bot pull request #54
Opened 2023-12-01 10:53 UTC by Amauryeen

2023-12-01 19:58 UTC, MachiganMC submitted a review, later dismissed
Hello, tout marche parfaitement (*à l'exception de 2 petits détails, voir la suggestion de code*).
J'ai juste 2 remarques en plus :
- Ce serait bien de mettre l'insertion des rôles par défaut dans `schema.sql` étant donné que ça fait parti de la construction de la base de données. Le site ne peut pas fonctionner sans ces données.
- J'ai pas très bien compris pourquoi un utilisateur pouvait avoir plusieurs rôles ? Ça veut dire qu'un admin peut être suspendu ? Ce serait pas mieux de donner qu'un seul rôle à un utilisateur ? Du coup, le rôle irait dans la table `users` et ça permettrait d'éviter le cas (*qui est possible ici*) où un utilisateur n'a aucun rôle (*en mettant par exemple, la valeur par défaut le rôle `user`*).

2023-12-05 16:04 UTC, Amauryeen commented
> * Ce serait bien de mettre l'insertion des rôles par défaut dans `schema.sql`

Les rôles par défaut sont déjà inserrés



> * J'ai pas très bien compris pourquoi un utilisateur pouvait avoir plusieurs rôles ?

Le feedback est intéressant. Le principe d'avoir plusieurs rôles est un peu comme un fonctionnement de groupes. Au besoin, on peut inclure un utilisateur dans plusieurs groupes, il peut être User et être à la fois Suspended. On peut imaginer dans le futur d'autres groupes ("roles") comme Superadmin, VIP, etc..

2023-12-05 23:41 UTC, MachiganMC requested changes
Yop, merci des précisions. Du coup, pour moi c'est OK s'il y aura de futurs rôles de ce genre.

Sinon, j'ai juste encore 2 soucis. 
J'avais pas vu lors de ma première review, mais il faudrait supprimer la fonction [checkIfAdmin](https://github.com/mux99/pocket-bot/blob/739bc1cf71e71860a9a1f3f495d653c4b4e05b7e/src/lib/server/account.js#L145-L153), car elle n'est plus utilisable.

Et le deuxième, faut voir des les suggestions de code.

2023-12-05 23:41 UTC, MachiganMC commented on scripts/seed.sql
> +  (1, 1),
Du coup, avec le commit aa77eb575e292630aad19713708dee3ed28396de, cette insertion ne fonctionne plus. 
```suggestion
  (1, 1),
```

2023-12-05 23:57 UTC, Amauryeen commented
> Yop, merci des précisions. Du coup, pour moi c'est OK s'il y aura de futurs rôles de ce genre.
> 
> Sinon, j'ai juste encore 2 soucis. J'avais pas vu lors de ma première review, mais il faudrait supprimer la fonction [checkIfAdmin](https://github.com/mux99/pocket-bot/blob/739bc1cf71e71860a9a1f3f495d653c4b4e05b7e/src/lib/server/account.js#L145-L153), car elle n'est plus utilisable.
> 
> Et le deuxième, faut voir des les suggestions de code.

C'est corrigé ! Merci !

2023-12-06 00:04 UTC, MachiganMC approved these changes
Au top !

2023-12-06 16:39 UTC, merged