Ajout layout header + notifications
mux99/pocket-bot pull request #67
Opened 2023-12-16 23:49 UTC by MachiganMC

## Description : 
Cette PR rajoute le Header (*pour les utilisateurs connectés*) avec un système de notifications.

## Tables :
Une nouvelle table nommée **notifications** qui contiendra les notifications avec les colonnes suivantes :
- `notification_id` : l'id de la notifications
- `receiver_id` : l'utilisateur chez qui la notification va s'afficher
- `type` : le type de notifications afin de les trier et d'envoyer vers la bonne page (*actuellement que **friends** et **parts***)
- `sender_id` : colonne non-obligatoire, représente l'utilisateur qui est la source de la notification (*par exemple pour une demande d'ami*)
- `seen` : si la notification va s'afficher dans le header.

## Routes :
- `/notifications` : voir ses notifications
- `/notifications/<id>/seen` : marquer une notification en lue
- `/notifications/<id>/unseen` : marquer une notification en non-lue
- `/notifications/<id>/delete` : supprimer une notification

## Note :
Une notification est automatiquement envoyée lors de la proposition d'une partie ou d'une demande d'ami.

2023-12-20 14:15 UTC, thePFLy commented
C'est globalement vraiment très bien. 
- Les notifications s'envoient correctement
- Le header est bien réalisé: le bouton est bien au millieu pour le responsive
- L'utilisateur à accès a son profile via le header
- le nombre de demandes de parties avec bulle bien numéroté fonctionne
- La déconnexion fonctionne
- La possibilitée de marquer comme lue une notif est présente

Quelques remarques:
- Lorsque je delete la notification je dois refresh la page pour ne plus avoir la bulle de la notif
- Les parts request ne sont pas affichées lorsque je clique sur le lien reçu.
- Il y'a un overflow en X lorsque le header est developpé
- la notification (bulle) de part request reste quand j'ai accepté.
- Pour que le header ne s'affiche pas sur la page controller,possiblitée d'ajouter ceci dans layout.svelte - à voir si c'est plutot à faire dans la branche controller:
```
{#if data.user && $page.url.pathname !== '/controller'}
    <Header user={data.user} />
{/if}
```

2023-12-20 14:46 UTC, thePFLy reviewed
C'est globalement très bien
- Les notifications s'envoient correctement
- Le header est bien réalisé: le bouton est bien au millieu pour le responsive
- L'utilisateur à accès a son profile via le header
- le nombre de demandes de parties avec bulle bien numéroté fonctionne
- La déconnexion fonctionne
- La possibilitée de marquer comme lue une notification est bien présente

quelques petites remarques
- Lorsque je delete la notification je dois refresh la page pour ne plus avoir la bulle de la notif
- Les parts request ne sont pas affichées lorsque je clique sur le lien
- Il y'a un overflow en X lorsque le header est developpé
- la notification (bulle) de part request reste quand j'ai accepté.
- Pour que le header ne s'affiche pas sur la page controller, ; possiblitée d'ajouter ceci dans layout.svelte - à voir si on fait plutot cela dans la branche controller:
```
{#if data.user && $page.url.pathname !== '/controller'}
    <Header user={data.user} />
{/if}
```

2023-12-20 16:23 UTC, thePFLy requested changes
C'est globalement très bien
- Les notifications s'envoient correctement
- Le header est bien réalisé: le bouton est bien au millieu pour le responsive
- L'utilisateur à accès a son profile via le header
- le nombre de demandes de parties avec bulle bien numéroté fonctionne
- La déconnexion fonctionne
- La possibilitée de marquer comme lue une notification est bien présente

quelques petites remarques
- Lorsque je delete la notification je dois refresh la page pour ne plus avoir la bulle de la notif
- Les parts request ne sont pas affichées lorsque je clique sur le lien
- Il y'a un overflow en X lorsque le header est developpé
- la notification (bulle) de part request reste quand j'ai accepté.
- Pour que le header ne s'affiche pas sur la page controller, ; possiblitée d'ajouter ceci dans layout.svelte - à voir si on fait plutot cela dans la branche controller:
```
{#if data.user && $page.url.pathname !== '/controller'}
    <Header user={data.user} />
{/if}
```

2023-12-20 16:45 UTC, mux99 approved these changes
ok pour moi

2023-12-21 07:24 UTC, mux99 approved these changes
ok

2023-12-21 07:45 UTC, thePFLy approved these changes
Good job I guess

2023-12-21 07:46 UTC, merged