Feature/api
mux99/pocket-bot pull request #7
Opened 2023-10-19 00:17 UTC by MachiganMC

## Description
Cette pull request permet à l'utilisateur de voir ses données de base (*comme son nom d'utilisateur*) ainsi que de les modifier (*nom d'utilisateur et mot de passe*). Cela à l'aide d'une nouvelle route d'api `/api/users`.

### Voir ses données :
Via la page `/profile`, si l'utilisateur est connecté, il pourra voir ses données.

### Modifier ses données :
Via la page `/profile/modify`, si l'utilisateur est connecté, il pourra modifier ses données.

### Routes d'API :
Les méthodes de la route `/users` ne prennent jamais de paramètres, car elles vont se baser sur la **session id** (*uuid*) se trouvant dans les cookies (si l'utilisateur est connecté) afin de savoir quel utilisateur veut voir/modifier ses données. 
Cela a été fait dans un aspect de sécurité où seul l'utilisateur connecté peut modifier/voir/supprimer ses données.

### Méthodes de le la route `/users` :
- GET 
- DELETE
- PATCH : pour cette méthode l'utilisateur devra fournir un corp à la requête avec soi "*username*", soi "*password*" (qui sera hachée par la suite).  Il est possible de modifier ces 2 informations en une requête.
Ce corp devra être écrit en json, il est donc important de rajouter dans les **headers** : `Content-type: application/json`. 

Il n'y a pas de méthode **POST**, les méthodes de création de compte s'occupant déjà de la possibilité de créer un utilisateur.

2023-10-19 08:38 UTC, Karitchi commented
J'ai regardé un peu le code et en fait c'est pas vraiment du sveltekit, y a pleins d'actions qu'on est vraiment pas sensé coder comme ça donc je préfère fermer la pr maintenant et t'expliquer en call

2023-11-08 18:28 UTC, noelibon requested changes
Le code marche bien mais j'ai des remarques:
* tu devrais ajouter un champ qui requiert le mdp actuel du user, pour confirmer la modification de ses infos
* tu devrais vérifier que le nouveau mdp n'est pas égal au mdp actuel, si il y a modif de mdp
* dans ```src/routes/profile/+page.server.js```, tu peux raccourcir les conditions des if (voir plus bas)
* dans ```src/routes/profile/modify/+page.server.js```, les fonctions ```checkUsername``` et ```checkPassword``` ont déjà une fonction similaire dans ```src/lib/server/account.js```
* dans ```src/routes/profile/utils.js```, idem, les fonctions définies ont déjà des fonctions similaires dans ```src/lib/server/account.js```
* il faudrait intégrer tailwind pour avoir un style à ta page
* On est bien d'accord que la route ```/users``` ne sert plus ?
Sinon c'est fonctionnel.

2023-11-08 18:32 UTC, noelibon requested changes

2023-11-08 18:32 UTC, noelibon commented on src/routes/profile/+page.server.js
> +    if (id === undefined)
```suggestion
    if (!id)
```

2023-11-08 18:32 UTC, noelibon commented on src/routes/profile/+page.server.js
> +    if (response == null)
```suggestion
    if (!response)
```

2023-11-09 00:25 UTC, MachiganMC commented
Hello, du coup, j'ai corrigé tes remarques @noelibon.
Pour résumer :
- Les conditions ont été raccourci (*selon tes suggestions*).
- La des pages est passée en anglais.
- Si l'on veut modifier son mot de passe, il est désormais requiert d'indiquer son ancien mot de passe (*avec une vérification si celui-ci change*).
- Pour faciliter les choses, j'ai supprimé le fichier `utils.js` qui se trouvait dans `/profile`, car la plupart des fonctions qui s'y trouvaient étaient déjà présentes dans `account.js` dans ``/lib` (*la seule qui n'y était pas, je l'y ai déplacée*).
- La route `/users` ne sert plus (*elle n'est d'ailleurs plus présente*). C'était l'ancienne route vers l'API pour l'utilisateurs, mais avec les changements demandés par @Karitchi (*respecter les conventions SvelteKit*), elle a été supprimée.
- J'ai fait un rebase par rapport à la branche **main** afin de :
   - Mettre à jour les derniers changements sur ma branche.
   - Intégrer TailWind (*je ferai le style des pages dans une autres PR*).
   - J'en ai profité pour modifier la page `account.js` (*et répercuter ces changements sur les fichiers qui l'utilisaient*) :
      - Mettre la constante **pool** en globale, je trouvais ça plus propre, car on devait toujours passer le paramètre *local* dans les fonctions qui faisaient des appels à la DB.
      - Du coup, supprimer le paramètre *local* des fonctions qui appellent la DB (*j'ai les pas ai encore tout modifiées*)

2023-11-18 15:16 UTC, noelibon approved these changes
C'est bon le code est fonctionnel et tu as bien changé ce qu'il fallait.

2023-11-19 00:02 UTC, MachiganMC commented
@noelibon Hey, je me permets de te redemander une review, comme il y a eu pas mal de changements aux niveaux de l'historique de commits. Et c'est pour être sûr que ça convient toujours.

2023-11-19 22:52 UTC, noelibon approved these changes
### Refactoring
* Les fonctionnalités marchent toujours.
* Tu as bien éliminer les variables/constantes qui n'étaient pas nécessaires.
* Tu as bien modifier le code pour qu'il ne dépende plus du paramètre ```locals``` à chaque requête vers la DB.
* J'ai juste une remarque concernant ```src/hooks.server.js```. Je vois que tu as ajouté du code pour exporter la constante ```apiUrl```, mais je ne comprends pas bien à quoi ça sert...

2023-11-20 20:19 UTC, MachiganMC commented
> J'ai juste une remarque concernant src/hooks.server.js. Je vois que tu as ajouté du code pour exporter la constante apiUrl, mais je ne comprends pas bien à quoi ça sert...
C'est pour avoir l'adresse du serveur, actuellement, c'est pas utilisé, mais c'est si jamais on fait une API.

2023-11-20 20:19 UTC, merged